### ISSUE TITLE
Strange error processing VFR terminal charts

### ISSUE THREAD

**Issue by ssokol** [N129BZ/chartmaker#18]
I was able to build the full Sectionals.mbtiles but hit an error processing the VFR terminal area charts:

```
* chart new_york
>> gdal_translate /chartmaker/workarea/Terminal/1_unzipped/new_york.tif
>> gdalwarp warping and clipping /chartmaker/workarea/Terminal/3_clipped/new_york.vrt using shapefile /chartmaker/clipshapes/terminal/new_york.shp
>> gdaladdo adding overviews to /chartmaker/workarea/Terminal/3_clipped/new_york.vrt
>> gdal2tiles tiling /chartmaker/workarea/Terminal/3_clipped/new_york.vrt into /chartmaker/workarea/Terminal/4_tiled/new_york
* chart new_york_vfr_plannings_
/chartmaker/make.js:493
        wgsbounds = infojson.wgs84Extent.coordinates[0];
                                         ^

TypeError: Cannot read properties of undefined (reading 'coordinates')
    at /chartmaker/make.js:493:42
    at Array.forEach (<anonymous>)
    at processImages (/chartmaker/make.js:477:16)
    at runProcessing (/chartmaker/make.js:362:5)
    at /chartmaker/make.js:345:9
    at Array.forEach (<anonymous>)
    at processFulls (/chartmaker/make.js:315:12)
    at Object.<anonymous> (/chartmaker/make.js:240:13)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)

Node.js v20.17.0
root@7b6ef70b2b86:/chartmaker#
```

That chart name ``new_york_vfr_plannings_`` doesn't look right.

**Comment by N129BZ** [comment]
FAA has recently added a new tif file to the zip, _**New York TAC VFR Planning Charts .tif**_ but this chart does not contain wgs84Extent data, which is causing an error when the app is trying to read the Extent coordinates.  Since the "normal" New York TAC chart is still there, the app will now skip over this file and not attempt to process it.
